version: '3.7'

networks:
  default:

services:
  db:
    image: ${COMPOSE_PROJECT_NAME}/mariadb:${IMAGE_TAG}
    networks:
      default: { }
    volumes:
      - dbdata:/var/lib/mysql:rw
    env_file:
      - .env
  httpd:
    image: ${COMPOSE_PROJECT_NAME}/httpd:${IMAGE_TAG}
    networks:
      default: { }
    volumes:
      - code:${HTTP_PROJECT_ROOT}:rw
    env_file:
      - .env
  php:
    image: ${COMPOSE_PROJECT_NAME}/php:${IMAGE_TAG}
    networks:
      default: { }
    volumes:
      - code:${HTTP_PROJECT_ROOT}:rw
    env_file:
      - .env
  toolbox:
    image: ${COMPOSE_PROJECT_NAME}/toolbox:${IMAGE_TAG}
    networks:
      default: { }
    volumes:
      - code:${HTTP_PROJECT_ROOT}:rw
    env_file:
      - .env

volumes:
  dbdata:
    driver: local
  code:
    driver: local

x-mutagen:
  sync:
    defaults:
      symlink:
        mode: "posix-raw"
      mode: "two-way-resolved"
      permissions:
        defaultFileMode: 0664
        defaultDirectoryMode: 0775
      configurationBeta:
        permissions:
          defaultOwner: "id:33"
          defaultGroup: "id:33"
    code:
      alpha: ${COMPOSE_PROJECT_ROOT}
      beta: "volume://code"
      ignore:
        vcs: true
        paths:
          - .idea
          - .mutagen.*
          - "*node_modules*"
  forward:
    database:
      source: "tcp:localhost:${PORT_MYSQL}"
      destination: "network://default:tcp:db:3306"
    web:
      source: "tcp::${PORT_HTTP}"
      destination: "network://default:tcp:httpd:80"
    ssh:
      source: "tcp:localhost:${PORT_SSH}"
      destination: "network://default:tcp:toolbox:22"
