name: Docker CI

on:
  push:
    branches: [ "master" ]
    # Publish tags as releases.
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: cp .env.dist .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build images and start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Push containers into the container registry
        if: github.event_name != 'pull_request'
        run: docker-compose -f "docker-compose.yml" push

      - name: Stop all running containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down -v
